// Builds the Docs from docs/*.md:
//   - the Docs home (docs.html) from docs/index.md
//   - one page per lesson (lesson-<name>.html) with a recipe card, sidebar and previous/next links
//   - the lessons teaser on the home page (index.html)
//   - the search entries (src/generated/docs-search.js)
//
// Run with `npm run build:docs` (also part of `npm run build`), or `node scripts/build-docs.mjs --watch`.
// Write a lesson by adding a markdown file to docs/ - see docs/README.md.

import fs from 'node:fs';
import path from 'node:path';
import {
    root, esc, attr, read, arrow, check, q, need, parseFrontMatter, toBlocks, renderBlock, missingImages,
} from './lib/content.mjs';

const docsDir = path.join(root, 'docs');
const MARKER = '<!-- generated by scripts/build-docs.mjs from docs/';
const GROUP = 'Start cooking';

// ---- Load ---------------------------------------------------------------------------------------------------------------------
function load() {
    const lessons = [];
    let home = null;
    for (const name of fs.readdirSync(docsDir).filter((f) => f.endsWith('.md') && f.toLowerCase() !== 'readme.md')) {
        const file = `docs/${name}`;
        const { data, body } = parseFrontMatter(read(path.join(docsDir, name)), file);
        if (name === 'index.md') {
            need(data, ['title', 'lead'], file);
            home = { file, title: data.title, lead: data.lead, description: data.description ?? data.lead, blocks: toBlocks(body, file) };
            continue;
        }
        need(data, ['title', 'order', 'summary', 'serves', 'time', 'level'], file);
        if (!/^\d+$/.test(data.order)) throw new Error(`${file}: "order" should be a whole number like 1, 2 or 3`);
        const slug = name.replace(/\.md$/, '');
        lessons.push({
            file,
            slug,
            page: `lesson-${slug}.html`,
            title: data.title,
            order: Number(data.order),
            summary: data.summary,
            serves: data.serves,
            time: data.time,
            level: data.level,
            ingredients: data.ingredients ?? [],
            searchHint: data.searchHint ?? data.summary,
            keywords: data.keywords ?? `${data.title} lesson beginner`.toLowerCase(),
            blocks: toBlocks(body, file),
        });
    }
    if (!home) throw new Error('docs/index.md is missing (it is the Docs home page)');
    lessons.sort((a, b) => a.order - b.order);
    return { home, lessons };
}

// ---- Shared pieces ---------------------------------------------------------------------------------------------------------------
const linkBase = 'block rounded-lg px-3 py-1.5 text-sm transition-colors focus-visible:ring-2 focus-visible:ring-accent focus-visible:outline-none';
const linkOn = 'bg-accent-soft font-medium text-accent';
const linkOff = 'text-muted hover:text-ink dark:hover:text-white';
const pad = (n) => String(n).padStart(2, '0');

function navList(lessons, current) {
    return `<div>
                        <ul class="space-y-0.5">
                            <li><a href="docs.html"${current === 'home' ? ' aria-current="page"' : ''} class="${linkBase} ${current === 'home' ? linkOn : linkOff}">Docs home</a></li>
                        </ul>
                    </div>
                    <div>
                        <p class="px-3 pb-1.5 text-[11px] font-semibold tracking-wider text-ink uppercase dark:text-white">${GROUP}</p>
                        <ul class="space-y-0.5">
${lessons.map((l) => `                            <li><a href="${l.page}"${current === l.slug ? ' aria-current="page"' : ''} class="${linkBase} ${current === l.slug ? linkOn : linkOff}"><span class="mr-2 font-mono text-xs opacity-60">${pad(l.order)}</span>${esc(l.title)}</a></li>`).join('\n')}
                        </ul>
                    </div>`;
}

function layout(lessons, current, currentLabel, article) {
    return `<main x-data="{ navOpen: false }" class="mx-auto w-full max-w-6xl px-4 sm:px-6 lg:px-8">
        <!-- Lesson switcher (phones and tablets) -->
        <div class="sticky top-11 z-30 -mx-4 border-b border-border bg-white/90 px-4 backdrop-blur-md sm:-mx-6 sm:px-6 lg:hidden dark:bg-[#0a0a0a]/90">
            <button type="button" @click="navOpen = !navOpen" aria-controls="doc-nav-mobile" aria-expanded="false"
                :aria-expanded="navOpen.toString()"
                class="flex w-full items-center justify-between py-3 text-sm font-medium text-ink focus-visible:outline-none dark:text-white">
                <span><span class="text-muted">Lessons · </span>${esc(currentLabel)}</span>
                <svg class="h-4 w-4 text-muted transition-transform" :class="navOpen ? 'rotate-180' : ''" viewBox="0 0 20 20" fill="none">
                    <path d="M5 8L10 13L15 8" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
            </button>
            <nav id="doc-nav-mobile" aria-label="Lessons" x-show="navOpen" x-cloak
                x-transition:enter="transition ease-out duration-150" x-transition:enter-start="-translate-y-1 opacity-0"
                x-transition:enter-end="translate-y-0 opacity-100" class="max-h-[60vh] space-y-5 overflow-y-auto pb-5">
                    ${navList(lessons, current)}
            </nav>
        </div>

        <div class="lg:grid lg:grid-cols-[13.5rem_minmax(0,1fr)] lg:gap-16">
            <aside class="hidden lg:block">
                <nav aria-label="Lessons" class="sticky top-[4.5rem] max-h-[calc(100vh-6rem)] space-y-6 overflow-y-auto py-10 pr-2">
                    ${navList(lessons, current)}
                </nav>
            </aside>

            <article class="min-w-0 pb-24">
                ${article}
            </article>
        </div>
    </main>`;
}

const eyebrow = (t) => `<p class="text-xs font-semibold tracking-wider text-accent uppercase">${t}</p>`;
const h2 = (t) => `<h2 class="mt-12 text-2xl font-semibold tracking-tight text-ink dark:text-white">${esc(t)}</h2>`;
const body = (blocks, ctx) => blocks.map((b) => (b.kind === 'h2' ? h2(b.text) : renderBlock(b, ctx))).join('\n                ');

// ---- Docs home -------------------------------------------------------------------------------------------------------------------
function lessonCards(lessons) {
    return `<ol class="mt-6 space-y-3">
${lessons.map((l) => `                    <li>
                        <a href="${l.page}" class="group flex items-center gap-4 rounded-2xl bg-surface p-5 ring-1 ring-border transition duration-300 hover:-translate-y-0.5 hover:shadow-md focus-visible:ring-2 focus-visible:ring-accent focus-visible:outline-none">
                            <span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-accent text-sm font-semibold text-white">${l.order}</span>
                            <span class="min-w-0 flex-1">
                                <span class="block font-semibold text-ink group-hover:text-accent dark:text-white">${esc(l.title)}</span>
                                <span class="mt-0.5 block text-sm leading-relaxed text-muted">${esc(l.summary)}</span>
                            </span>
                            <span class="hidden shrink-0 rounded-full bg-white px-3 py-1 text-xs font-medium text-muted ring-1 ring-border sm:block dark:bg-white/5">${esc(l.time)}</span>
                        </a>
                    </li>`).join('\n')}
                </ol>`;
}

function homeMain(home, lessons) {
    const article = `<section class="pt-10 lg:pt-16">
                    ${eyebrow('Docs')}
                    <h1 class="mt-3 text-4xl font-semibold tracking-tight text-balance text-ink sm:text-5xl dark:text-white">${esc(home.title)}</h1>
                    <p class="mt-4 max-w-2xl text-lg leading-relaxed text-muted">${esc(home.lead)}</p>
                </section>
                ${body(home.blocks, { renderLessons: () => lessonCards(lessons) })}`;
    return layout(lessons, 'home', 'Docs home', article);
}

// ---- Lesson pages ------------------------------------------------------------------------------------------------------------------
function pager(lessons, i) {
    const prev = lessons[i - 1];
    const next = lessons[i + 1];
    const card = (href, label, title, align) => `<a href="${href}" class="group block rounded-2xl bg-surface p-5 ring-1 ring-border transition duration-300 hover:-translate-y-0.5 hover:shadow-md focus-visible:ring-2 focus-visible:ring-accent focus-visible:outline-none ${align === 'right' ? 'text-right' : ''}">
                        <span class="text-xs font-medium text-muted">${label}</span>
                        <span class="mt-1 block font-semibold text-ink group-hover:text-accent dark:text-white">${title}</span>
                    </a>`;
    return `<nav aria-label="Lesson navigation" class="mt-14 grid gap-4 border-t border-border pt-8 sm:grid-cols-2">
                    ${prev ? card(prev.page, '← Previous lesson', esc(prev.title), 'left') : card('docs.html', '← Docs home', 'All the lessons', 'left')}
                    ${next ? card(next.page, 'Next lesson →', esc(next.title), 'right') : card('docs.html', 'You finished the path →', 'Back to all lessons', 'right')}
                </nav>`;
}

function lessonMain(lesson, lessons) {
    const i = lessons.indexOf(lesson);
    const article = `<nav aria-label="Breadcrumb" class="flex items-center gap-2 pt-10 text-xs text-muted lg:pt-16">
                    <a href="docs.html" class="transition-colors hover:text-ink dark:hover:text-white">Docs</a>
                    <span aria-hidden="true">›</span>
                    <span class="text-ink dark:text-white">Lesson ${lesson.order}</span>
                </nav>
                <div class="mt-6">
                    ${eyebrow(`Lesson ${lesson.order} of ${lessons.length}`)}
                    <h1 class="mt-3 text-4xl font-semibold tracking-tight text-balance text-ink sm:text-5xl dark:text-white">${esc(lesson.title)}</h1>
                    <p class="mt-4 max-w-2xl text-lg leading-relaxed text-muted">${esc(lesson.summary)}</p>
                </div>

                <div class="mt-8 max-w-2xl rounded-3xl bg-surface p-6 ring-1 ring-border sm:p-8">
                    <p class="text-xs font-semibold tracking-wider text-accent uppercase">Recipe card</p>
                    <dl class="mt-5 grid grid-cols-3 gap-6">
${[['Serves', lesson.serves], ['Time', lesson.time], ['Level', lesson.level]].map(([k, v]) => `                        <div>
                            <dt class="text-xs text-muted">${k}</dt>
                            <dd class="mt-1 text-[15px] font-semibold text-ink dark:text-white">${esc(v)}</dd>
                        </div>`).join('\n')}
                    </dl>${lesson.ingredients.length ? `
                    <p class="mt-7 text-xs font-semibold tracking-wider text-muted uppercase">Ingredients</p>
                    <ul class="mt-3 space-y-2.5">
${lesson.ingredients.map((x) => `                        <li class="flex items-start gap-3 text-[15px] leading-relaxed text-ink dark:text-white">${check}<span>${esc(x)}</span></li>`).join('\n')}
                    </ul>` : ''}
                </div>

                <div class="max-w-2xl">
                ${body(lesson.blocks, {})}
                ${pager(lessons, i)}
                </div>`;
    return layout(lessons, lesson.slug, lesson.title, article);
}

// ---- Home page teaser ---------------------------------------------------------------------------------------------------------------
function teaser(lessons) {
    return `<section id="docs" class="scroll-mt-14 border-t border-border bg-surface">
        <div class="mx-auto max-w-6xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20">
            ${eyebrow('Docs')}
            <h2 class="mt-2 text-3xl font-semibold tracking-tight text-ink sm:text-4xl dark:text-white">Learn to build, one recipe at a time</h2>
            <p class="mt-3 max-w-2xl leading-relaxed text-muted">
                Friendly lessons for anyone starting out. Each one is a recipe card, with cooking comparisons that make the tricky parts easy.
            </p>
            <ol class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
${lessons.map((l) => `                <li>
                    <a href="${l.page}" class="group flex h-full flex-col rounded-2xl bg-white p-5 ring-1 ring-border transition-shadow hover:shadow-md focus-visible:ring-2 focus-visible:ring-accent focus-visible:outline-none dark:bg-white/5">
                        <span class="flex h-8 w-8 items-center justify-center rounded-full bg-accent text-xs font-semibold text-white">${l.order}</span>
                        <h3 class="mt-4 font-semibold text-ink group-hover:text-accent dark:text-white">${esc(l.title)}</h3>
                        <p class="mt-1 flex-1 text-sm leading-relaxed text-muted">${esc(l.summary)}</p>
                        <p class="mt-4 text-xs font-medium text-muted">${esc(l.time)}</p>
                    </a>
                </li>`).join('\n')}
            </ol>
            <a href="docs.html" class="mt-6 inline-flex items-center gap-1 text-sm font-medium text-accent transition-colors hover:text-accent-hover focus-visible:underline focus-visible:outline-none">Open the docs ${arrow}</a>
        </div>
    </section>`;
}

// ---- Build ----------------------------------------------------------------------------------------------------------------------------
function build() {
    missingImages.length = 0;
    const { home, lessons } = load();
    const boundary = /(<\/header>)[\s\S]*?(<footer)/;
    const shell = read(path.join(root, 'skills.html'));
    if (!boundary.test(shell)) throw new Error('skills.html: cannot find the header/footer boundary');

    const write = (file, title, description, main, from) => {
        const html = shell
            .replace(/<title>[\s\S]*?<\/title>/, () => `<title>${esc(title)} | Yora Jihun</title>
    <meta name="description" content="${attr(description)}">
    ${MARKER}${from} - edit that file, not this one -->`)
            .replace(boundary, (_, a, b) => `${a}\n\n    ${main}\n\n    ${b}`);
        fs.writeFileSync(path.join(root, file), html.replace(/[ \t]+$/gm, ''));
    };

    write('docs.html', home.title, home.description, homeMain(home, lessons), home.file);
    for (const l of lessons) write(l.page, l.title, l.summary, lessonMain(l, lessons), l.file);

    // Remove pages of lessons that were deleted
    const keep = new Set(lessons.map((l) => l.page));
    for (const f of fs.readdirSync(root).filter((n) => /^lesson-.*\.html$/.test(n) && !keep.has(n))) {
        if (read(path.join(root, f)).includes(MARKER)) {
            fs.unlinkSync(path.join(root, f));
            console.log(`removed ${f} (no matching lesson in docs/)`);
        }
    }

    // Home page teaser
    const indexPath = path.join(root, 'index.html');
    const page = read(indexPath);
    const section = /<section id="docs"[\s\S]*?<\/section>/;
    if (!section.test(page)) throw new Error('index.html: cannot find the Docs section');
    fs.writeFileSync(indexPath, page.replace(section, () => teaser(lessons)));

    // Search
    const entries = lessons.map((l) => `    { group: 'Lesson', title: ${q(l.title)}, hint: ${q(l.searchHint)}, href: ${q(l.page)}, keywords: ${q(l.keywords)} },`);
    fs.mkdirSync(path.join(root, 'src/generated'), { recursive: true });
    fs.writeFileSync(
        path.join(root, 'src/generated/docs-search.js'),
        `// Generated by scripts/build-docs.mjs from docs/*.md. Do not edit by hand.\nexport const docsSearch = [\n${entries.join('\n')}\n];\n`,
    );

    console.log(`docs built: ${lessons.length} lessons (${lessons.map((l) => l.slug).join(', ')})`);
    for (const src of new Set(missingImages)) console.log(`note: image not found yet, skipped: ${src}`);
}

if (process.argv.includes('--watch')) {
    const run = () => {
        try {
            build();
            // Nudge the CSS build so any new Tailwind classes in the generated pages get compiled.
            const now = new Date();
            fs.utimesSync(path.join(root, 'src/main.css'), now, now);
        } catch (error) {
            console.error(`\n${error.message}\n`);
        }
    };
    run();
    let timer;
    fs.watch(docsDir, () => {
        clearTimeout(timer);
        timer = setTimeout(run, 250);
    });
    console.log('watching docs/ for changes...');
} else {
    try {
        build();
    } catch (error) {
        console.error(`\n${error.message}\n`);
        process.exit(1);
    }
}
