// Builds the blog from posts/*.md:
//   - one page per post (<slug>.html)
//   - the blog list (blog.html)
//   - the Guides list on the home page (index.html)
//   - the search entries (src/generated/posts-search.js)
//
// Run with `npm run build:blog` (also part of `npm run build`), or `node scripts/build-blog.mjs --watch`.
// Write a post by adding a markdown file to posts/ - see posts/README.md.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const postsDir = path.join(root, 'posts');
const MARKER = '<!-- generated by scripts/build-blog.mjs from posts/';

// ---- Small helpers ----------------------------------------------------------------------------------------------------
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const attr = (s) => esc(s).replace(/"/g, '&quot;');
const slugify = (s) => s.toLowerCase().replace(/&[a-z]+;/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const read = (p) => fs.readFileSync(p, 'utf8');
const inline = (md) => marked.parseInline(md);

const icons = {
    bolt: '<path d="M11 2 4 12h5l-1 6 7-10h-5l1-6Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round" fill="currentColor" fill-opacity="0.15" />',
    users: '<path d="M7.5 9a2.75 2.75 0 1 0 0-5.5 2.75 2.75 0 0 0 0 5.5ZM2.5 16c0-2.6 2.2-4.5 5-4.5s5 1.9 5 4.5M13.5 8.5a2.25 2.25 0 1 0 0-4.5M14.5 11.7c1.7.4 3 1.9 3 4.3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />',
    cube: '<path d="M10 2.5 16.5 6v8L10 17.5 3.5 14V6L10 2.5Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round" /><path d="M3.5 6 10 9.5 16.5 6M10 9.5v8" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round" />',
    heart: '<path d="M10 16.5s-6.5-3.7-6.5-8.6A3.4 3.4 0 0 1 10 6.3a3.4 3.4 0 0 1 6.5 1.6c0 4.9-6.5 8.6-6.5 8.6Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round" />',
    bulb: '<path d="M8 15.5h4M8.5 18h3M10 2.5a5 5 0 0 0-3 9c.6.5 1 1.2 1 2v.5h4v-.5c0-.8.4-1.5 1-2a5 5 0 0 0-3-9Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />',
    flask: '<path d="M8 2.5h4M9 2.5v5L4.6 15a1.5 1.5 0 0 0 1.3 2.3h8.2a1.5 1.5 0 0 0 1.3-2.3L11 7.5v-5M6.4 12.5h7.2" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />',
    clock: '<circle cx="10" cy="10" r="7" stroke="currentColor" stroke-width="1.5" /><path d="M10 6v4l3 2" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />',
    trophy: '<path d="M6.5 3h7v4a3.5 3.5 0 0 1-7 0V3Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round" /><path d="M6.5 5h-3v1a3 3 0 0 0 3 3M13.5 5h3v1a3 3 0 0 1-3 3M10 10.5V14M7 17h6M8 14h4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />',
};

const arrow = '<svg class="h-3 w-3" viewBox="0 0 10 11" fill="none"><path d="M2.5 8L7.5 3M7.5 3H3.3M7.5 3V7.2" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round" /></svg>';
const check = '<svg class="mt-1.5 h-3.5 w-3.5 shrink-0 text-accent" viewBox="0 0 20 20" fill="none"><path d="M4 10l4 4 8-8" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" /></svg>';

// ---- Front matter -------------------------------------------------------------------------------------------------------
// Supports `key: value`, `key: [a, b, c]`, and a list under a key (`facts:` then `  - Label: Value`).
function parseFrontMatter(raw, file) {
    const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
    if (!m) throw new Error(`${file}: missing front matter (--- ... --- at the top)`);
    const data = {};
    let key = null;
    for (const line of m[1].split(/\r?\n/)) {
        if (!line.trim() || line.trim().startsWith('#')) continue;
        const item = line.match(/^\s+-\s+(.*)$/);
        if (item && key) {
            if (!Array.isArray(data[key])) data[key] = [];
            data[key].push(item[1].trim());
            continue;
        }
        const kv = line.match(/^([A-Za-z][\w-]*):\s*(.*)$/);
        if (!kv) throw new Error(`${file}: cannot read front matter line: ${line}`);
        key = kv[1];
        const v = kv[2].trim();
        if (v === '') data[key] = [];
        else if (v.startsWith('[') && v.endsWith(']')) data[key] = v.slice(1, -1).split(',').map((s) => s.trim()).filter(Boolean);
        else if (v === 'true' || v === 'false') data[key] = v === 'true';
        else data[key] = v.replace(/^(["'])(.*)\1$/, '$2');
    }
    return { data, body: m[2] };
}

// ---- Body: markdown -> blocks ---------------------------------------------------------------------------------------------
// Blocks are rendered by hand (not by marked's HTML output) so they get the site's own classes.
function mdBlocks(src, file) {
    const blocks = [];
    for (const t of marked.lexer(src)) {
        switch (t.type) {
            case 'space':
            case 'hr':
                break;
            case 'heading':
                if (t.depth === 2) blocks.push({ kind: 'h2', text: t.text.replace(/\s*\{-\}\s*$/, ''), plain: /\{-\}\s*$/.test(t.text) });
                else if (t.depth === 3) blocks.push({ kind: 'h3', html: inline(t.text) });
                else throw new Error(`${file}: use ## or ### for headings (the page title comes from the front matter)`);
                break;
            case 'paragraph': {
                const only = t.tokens.length === 1 ? t.tokens[0] : null;
                if (only?.type === 'image') blocks.push({ kind: 'figure', src: only.href, alt: only.text, caption: only.title });
                else blocks.push({ kind: 'p', html: inline(t.text) });
                break;
            }
            case 'list':
                blocks.push({ kind: 'list', items: t.items.map((i) => inline(i.text.trim())) });
                break;
            case 'blockquote':
                blocks.push({ kind: 'quote', html: t.tokens.filter((x) => x.type === 'paragraph').map((x) => inline(x.text)).join(' ') });
                break;
            case 'html':
                if (!t.raw.trim().startsWith('<!--')) blocks.push({ kind: 'html', raw: t.raw });
                break;
            default:
                throw new Error(`${file}: unsupported markdown (${t.type}). Use paragraphs, ## headings, lists, > quotes, images or ::: containers.`);
        }
    }
    return blocks;
}

// ::: containers - note (highlighted box), tip ("Try this"), steps (numbered cards)
function container(name, arg, inner, file) {
    const tokens = marked.lexer(inner).filter((t) => t.type !== 'space');
    if (name === 'note') {
        const parts = tokens.map((t) => {
            if (t.type !== 'paragraph') throw new Error(`${file}: a :::note can only contain paragraphs`);
            const only = t.tokens.length === 1 ? t.tokens[0] : null;
            return only?.type === 'link' ? { link: only.href, text: only.text } : { html: inline(t.text) };
        });
        return { kind: 'note', title: arg, parts };
    }
    if (name === 'tip') return { kind: 'tip', html: tokens.map((t) => inline(t.text)).join(' ') };
    if (name === 'steps') {
        const list = tokens.find((t) => t.type === 'list');
        if (!list) throw new Error(`${file}: :::steps needs a numbered list`);
        return {
            kind: 'steps',
            items: list.items.map((i) => {
                const m = i.text.trim().match(/^\*\*(.+?)\*\*[:.]?\s*([\s\S]*)$/);
                if (!m) throw new Error(`${file}: each step should look like "**Title**: description"`);
                return { title: esc(m[1]), html: inline(m[2]) };
            }),
        };
    }
    throw new Error(`${file}: unknown container :::${name}`);
}

function toBlocks(body, file) {
    const out = [];
    const lines = body.split(/\r?\n/);
    let buf = [];
    const flush = () => {
        if (buf.join('').trim()) out.push(...mdBlocks(buf.join('\n'), file));
        buf = [];
    };
    for (let i = 0; i < lines.length; i++) {
        const m = lines[i].match(/^:::(\w+)\s*(.*)$/);
        if (!m) {
            buf.push(lines[i]);
            continue;
        }
        flush();
        const inner = [];
        i++;
        while (i < lines.length && lines[i].trim() !== ':::') inner.push(lines[i++]);
        out.push(container(m[1], m[2].trim(), inner.join('\n'), file));
    }
    flush();
    return out;
}

// ---- Load posts -------------------------------------------------------------------------------------------------------------------
function loadPosts() {
    const posts = [];
    for (const name of fs.readdirSync(postsDir).filter((f) => f.endsWith('.md') && f.toLowerCase() !== 'readme.md')) {
        const file = `posts/${name}`;
        const { data, body } = parseFrontMatter(read(path.join(postsDir, name)), file);
        const slug = name.replace(/\.md$/, '');
        const hasPage = data.page !== false;
        for (const key of ['title', 'date']) if (!data[key]) throw new Error(`${file}: front matter needs "${key}"`);
        if (hasPage) for (const key of ['lead', 'category', 'gradient', 'icon']) if (!data[key]) throw new Error(`${file}: front matter needs "${key}"`);
        if (hasPage && !icons[data.icon]) throw new Error(`${file}: unknown icon "${data.icon}" (use one of: ${Object.keys(icons).join(', ')})`);

        const d = String(data.date).match(/^(\d{4})-(\d{2})(?:-(\d{2}))?$/);
        if (!d) throw new Error(`${file}: date should look like 2025-11-12 (or 2025-11)`);
        const month = MONTHS[Number(d[2]) - 1];
        const facts = (data.facts ?? []).map((f) => {
            const i = f.indexOf(': ');
            if (i < 0) throw new Error(`${file}: each fact should look like "Label: Value"`);
            return [f.slice(0, i), f.slice(i + 2)];
        });

        posts.push({
            slug,
            file,
            hasPage,
            title: data.title,
            sort: Number(d[1]) * 10000 + Number(d[2]) * 100 + Number(d[3] ?? 1),
            order: Number(data.order ?? 0),
            dateFull: d[3] ? `${month} ${Number(d[3])}, ${d[1]}` : `${month} ${d[1]}`,
            dateShort: `${month} ${d[1]}`,
            category: data.category ?? '',
            tags: data.tags ?? [],
            lead: data.lead ?? '',
            excerpt: data.excerpt ?? data.lead ?? '',
            gradient: data.gradient,
            icon: data.icon,
            image: data.image,
            toc: data.toc === true,
            numbered: data.numbered === true,
            searchHint: data.searchHint ?? data.excerpt ?? data.lead ?? '',
            keywords: data.keywords ?? `${data.title} ${(data.tags ?? []).join(' ')}`.toLowerCase(),
            facts,
            blocks: hasPage ? toBlocks(body, file) : [],
        });
    }
    posts.sort((a, b) => b.sort - a.sort || b.order - a.order || a.slug.localeCompare(b.slug));
    return posts;
}

// ---- Rendering: covers, blocks, pages ---------------------------------------------------------------------------------------------
const cover = (post, outer, iconSize) => `<div class="relative flex items-center justify-center overflow-hidden bg-gradient-to-br ${post.gradient} ${outer}" aria-hidden="true">
                    <span class="absolute -top-8 -right-8 h-32 w-32 rounded-full bg-white/15"></span>
                    <span class="absolute -bottom-10 -left-6 h-28 w-28 rounded-full bg-white/10"></span>
                    <svg class="${iconSize} relative text-white" viewBox="0 0 20 20" fill="none">${icons[post.icon]}</svg>
                </div>`;

const tagChips = (tags) => tags.map((t) => `<li class="rounded-full bg-surface px-3 py-1 text-xs font-medium text-ink ring-1 ring-border dark:text-white">${esc(t)}</li>`).join('\n                        ');
const missingImages = [];

function renderBlock(b) {
    switch (b.kind) {
        case 'p':
            return `<p class="mt-4 text-[17px] leading-8 text-ink/80 dark:text-white/80">${b.html}</p>`;
        case 'h3':
            return `<h3 class="mt-8 text-lg font-semibold text-ink dark:text-white">${b.html}</h3>`;
        case 'list':
            return `<ul class="mt-6 space-y-3 rounded-2xl bg-surface p-6 ring-1 ring-border">
${b.items.map((f) => `                    <li class="flex items-start gap-3 text-[15px] leading-relaxed text-ink dark:text-white">${check}<span>${f}</span></li>`).join('\n')}
                </ul>`;
        case 'quote':
            return `<blockquote class="mt-8 border-l-2 border-accent pl-5 text-xl leading-relaxed font-medium text-ink dark:text-white">${b.html}</blockquote>`;
        case 'figure': {
            if (!/^https?:/.test(b.src) && !fs.existsSync(path.join(root, b.src))) {
                missingImages.push(b.src);
                return '';
            }
            return `<figure class="mt-6 overflow-hidden rounded-2xl ring-1 ring-border">
                    <img src="${attr(b.src)}" alt="${attr(b.alt)}" loading="lazy" class="w-full object-cover">${b.caption ? `
                    <figcaption class="bg-surface px-4 py-3 text-xs text-muted">${esc(b.caption)}</figcaption>` : ''}
                </figure>`;
        }
        case 'html':
            return b.raw;
        case 'tip':
            return `<aside class="mt-6 flex gap-3 rounded-2xl bg-accent-soft p-4 text-[15px] leading-relaxed text-ink dark:text-white">
                    <svg class="mt-0.5 h-4 w-4 shrink-0 text-accent" viewBox="0 0 20 20" fill="none" aria-hidden="true">${icons.bolt}</svg>
                    <p><strong class="font-semibold">Try this.</strong> ${b.html}</p>
                </aside>`;
        case 'steps':
            return `<ol class="mt-6 grid gap-4 sm:grid-cols-3">
${b.items.map((s, i) => `                    <li class="rounded-2xl bg-white p-5 ring-1 ring-border dark:bg-white/5">
                        <span class="flex h-7 w-7 items-center justify-center rounded-full bg-accent text-xs font-semibold text-white">${i + 1}</span>
                        <h3 class="mt-3 font-semibold text-ink dark:text-white">${s.title}</h3>
                        <p class="mt-1 text-sm leading-relaxed text-muted">${s.html}</p>
                    </li>`).join('\n')}
                </ol>`;
        case 'note':
            return `<aside class="mt-12 rounded-2xl bg-accent-soft p-6">
                    <p class="font-semibold text-ink dark:text-white">${esc(b.title)}</p>${b.parts
                        .map((p) => (p.link
                            ? `\n                    <a href="${attr(p.link)}" class="mt-4 inline-flex items-center gap-1 text-sm font-medium text-accent transition-colors hover:text-accent-hover">${esc(p.text)} ${arrow}</a>`
                            : `\n                    <p class="mt-1 text-[15px] leading-relaxed text-ink/80 dark:text-white/80">${p.html}</p>`))
                        .join('')}
                </aside>`;
        default:
            throw new Error(`unknown block ${b.kind}`);
    }
}

const factsHtml = (facts) => `<dl class="grid grid-cols-2 gap-x-6 gap-y-5 rounded-2xl bg-surface p-6 ring-1 ring-border ${facts.length === 4 ? 'sm:grid-cols-4' : 'sm:grid-cols-3'}">
${facts.map(([k, v]) => `                    <div>
                        <dt class="text-xs text-muted">${esc(k)}</dt>
                        <dd class="mt-1 text-[15px] font-semibold text-ink dark:text-white">${esc(v)}</dd>
                    </div>`).join('\n')}
                </dl>`;

// Long posts: each ## heading becomes a section the sticky "In this article" list follows.
function sectionsOf(post) {
    const sections = [];
    const preface = [];
    let current = null;
    let n = 0;
    for (const b of post.blocks) {
        if (b.kind === 'h2') {
            current = { id: slugify(b.text), title: b.text, num: post.numbered && !b.plain ? ++n : 0, blocks: [] };
            sections.push(current);
        } else (current ? current.blocks : preface).push(b);
    }
    return { sections, preface };
}

const words = (post) =>
    [post.lead, ...post.facts.flat(), ...post.blocks.flatMap((b) => [b.text, b.html, b.title, ...(b.items ?? []).map((i) => (typeof i === 'string' ? i : `${i.title} ${i.html}`)), ...(b.parts ?? []).map((p) => p.html ?? '')])]
        .filter(Boolean).join(' ').replace(/<[^>]+>/g, ' ').split(/\s+/).filter(Boolean).length;

function pageMain(post, all) {
    const minutes = Math.max(1, Math.round(words(post) / 200));
    const others = all.filter((p) => p.hasPage && p.slug !== post.slug).slice(0, 5);
    const keepReading = `<p class="mt-8 text-[11px] font-semibold tracking-wider text-ink uppercase dark:text-white">Keep reading</p>
                    <ul class="mt-3 space-y-3 text-sm">
${others.map((o) => `                        <li><a href="${o.slug}.html" class="text-muted transition-colors hover:text-accent">${esc(o.title)}</a></li>`).join('\n')}
                        <li><a href="blog.html" class="inline-flex items-center gap-1 text-accent transition-colors hover:text-accent-hover">All posts ${arrow}</a></li>
                    </ul>`;

    let content;
    let aside;
    if (post.toc) {
        const { sections, preface } = sectionsOf(post);
        content = preface.map(renderBlock).join('\n                ') + sections
            .map((s, i) => `
                <section id="${s.id}" data-doc-section data-title="${attr(s.title)}" class="scroll-mt-28 lg:scroll-mt-20${i === 0 && !preface.length ? '' : ' pt-12'}">
                    <h2 class="text-2xl font-semibold tracking-tight text-ink dark:text-white">${s.num ? `<span class="mr-3 font-mono text-sm font-semibold text-accent">${String(s.num).padStart(2, '0')}</span>` : ''}${esc(s.title)}</h2>
                    ${s.blocks.map(renderBlock).join('\n                    ')}
                </section>`).join('');
        aside = `<aside class="hidden lg:block">
                <div class="sticky top-[4.5rem] max-h-[calc(100vh-6rem)] overflow-y-auto pt-2 pr-2">
                    <p class="pb-3 text-[11px] font-semibold tracking-wider text-ink uppercase dark:text-white">In this article</p>
                    <ul>
${sections.map((s) => `                        <li>
                            <a href="#${s.id}" @click="select('${s.id}')" :aria-current="active === '${s.id}' ? 'true' : null"
                                :class="active === '${s.id}' ? 'font-medium text-accent' : 'text-muted hover:text-ink dark:hover:text-white'"
                                class="block border-l-2 py-1.5 pl-4 text-sm transition-colors focus-visible:outline-none focus-visible:text-accent"
                                :style="active === '${s.id}' ? 'border-color: var(--color-accent)' : 'border-color: transparent'">${esc(s.title)}</a>
                        </li>`).join('\n')}
                    </ul>
                    ${keepReading}
                </div>
            </aside>`;
    } else {
        content = post.blocks
            .map((b) => (b.kind === 'h2' ? `<h2 class="mt-12 text-2xl font-semibold tracking-tight text-ink dark:text-white">${esc(b.text)}</h2>` : renderBlock(b)))
            .join('\n                ');
        aside = `<aside class="mt-14 lg:mt-0">
                <div class="lg:sticky lg:top-[4.5rem]">
                    <p class="text-[11px] font-semibold tracking-wider text-ink uppercase dark:text-white">Tags</p>
                    <ul class="mt-3 flex flex-wrap gap-2">
                        ${tagChips(post.tags)}
                    </ul>

                    ${keepReading}
                </div>
            </aside>`;
    }

    return `<main${post.toc ? ' x-data="docsPage"' : ''} class="mx-auto w-full max-w-6xl px-4 pt-14 pb-24 sm:px-6 lg:px-8 lg:pt-20">
        <header class="max-w-3xl">
            <nav aria-label="Breadcrumb" class="flex items-center gap-2 text-xs text-muted">
                <a href="blog.html" class="transition-colors hover:text-ink dark:hover:text-white">Blog</a>
                <span aria-hidden="true">›</span>
                <span class="text-ink dark:text-white">${esc(post.title)}</span>
            </nav>

            <div class="mt-6 flex flex-wrap items-center gap-x-3 gap-y-2 text-xs">
                <span class="rounded-full bg-accent-soft px-2.5 py-1 font-semibold tracking-wide text-accent uppercase">${esc(post.category)}</span>
                <span class="text-muted">${post.dateFull}</span>
                <span class="text-muted" aria-hidden="true">·</span>
                <span class="text-muted">${minutes} min read</span>
            </div>

            <h1 class="mt-5 text-4xl font-semibold tracking-tight text-balance text-ink sm:text-6xl dark:text-white">${esc(post.title)}</h1>
            <p class="mt-5 text-xl leading-relaxed text-muted">${esc(post.lead)}</p>${post.toc && post.tags.length ? `
            <ul class="mt-6 flex flex-wrap gap-2">
                        ${tagChips(post.tags)}
            </ul>` : ''}

            <div class="mt-8 flex items-center gap-3">
                <img src="assets/images/about/portrait.jpg" alt="" width="80" height="104" class="h-10 w-10 rounded-full object-cover ring-1 ring-border">
                <div>
                    <p class="text-sm font-semibold text-ink dark:text-white">Yora Jihun</p>
                    <p class="text-xs text-muted">Lead System Engineer &amp; AI Specialist</p>
                </div>
            </div>
        </header>

        ${cover(post, 'mt-10 aspect-[21/9] rounded-3xl', 'h-16 w-16')}

        <div class="mt-14 lg:grid lg:grid-cols-[minmax(0,1fr)_15rem] lg:gap-16">
            <article class="max-w-2xl">
                ${post.facts.length ? factsHtml(post.facts) + '\n                ' : ''}${content}

                <a href="blog.html" class="mt-12 inline-flex items-center gap-1 text-sm font-medium text-accent transition-colors hover:text-accent-hover">← Back to all posts</a>
            </article>

            ${aside}
        </div>
    </main>`;
}

// ---- Blog list ---------------------------------------------------------------------------------------------------------------------
const cardHref = (p) => (p.hasPage ? `${p.slug}.html` : '#');

function featuredCard(p) {
    return `<a href="${cardHref(p)}"
                    class="group block overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-border transition-all hover:-translate-y-1 hover:shadow-lg sm:col-span-2 lg:col-span-12 sm:grid sm:grid-cols-2 dark:bg-white/5">
                    ${cover(p, 'h-48 sm:h-full sm:min-h-64', 'h-14 w-14')}
                    <div class="p-6 sm:p-10">
                        <div class="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs">
                            <span class="rounded-full bg-accent-soft px-2.5 py-1 font-semibold tracking-wide text-accent uppercase">Latest</span>
                            <span class="font-medium text-muted">${p.dateFull}</span>
                            <span class="text-muted" aria-hidden="true">·</span>
                            <span class="text-muted">${Math.max(1, Math.round(words(p) / 200))} min read</span>
                        </div>
                        <h3 class="mt-4 text-2xl font-semibold tracking-tight text-ink group-hover:text-accent sm:text-3xl dark:text-white">${esc(p.title)}</h3>
                        <p class="mt-3 leading-relaxed text-muted">${esc(p.excerpt)}</p>
                        <span class="mt-6 inline-flex items-center gap-1 text-sm font-medium text-accent">Read the article ${arrow}</span>
                    </div>
                </a>`;
}

// Rows of three; leftover cards at the end share wider rows in pairs, so nothing is ever left alone.
function cardSpan(i, total) {
    const rest = total % 3;
    const paired = Math.min(total, rest === 0 ? 0 : rest === 2 ? 2 : 4);
    const wide = i >= total - paired;
    return `${wide ? 'lg:col-span-6' : 'lg:col-span-4'}${i === total - 1 && total % 2 === 1 ? ' sm:col-span-2' : ''}`;
}

function smallCard(p, i, total) {
    const top = p.image
        ? `<img src="assets/images/blog/${attr(p.image)}" alt="${attr(p.title)}" loading="lazy" class="h-36 w-full object-cover">`
        : cover(p, 'h-36 w-full', 'h-10 w-10');
    return `<a href="${cardHref(p)}"
                    class="group block overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-border transition-all hover:-translate-y-1 hover:shadow-lg dark:bg-white/5 ${cardSpan(i, total)}">
                    ${top}
                    <div class="p-6">
                        <p class="text-xs font-medium text-muted">${p.dateShort}</p>
                        <h3 class="mt-2 text-lg font-semibold text-ink group-hover:text-accent dark:text-white">${esc(p.title)}</h3>
                        <p class="mt-2 text-sm text-muted">${esc(p.excerpt)}</p>
                    </div>
                </a>`;
}

function blogMain(posts) {
    const [latest, ...rest] = posts;
    return `<main>
        <section class="border-t border-border pt-24">
            <div class="mx-auto max-w-6xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20">
                <div class="max-w-2xl">
                    <p class="text-sm font-semibold tracking-wider text-accent uppercase">Blog</p>
                    <h2 class="mt-2 text-3xl font-semibold tracking-tight text-ink sm:text-4xl dark:text-white">
                        Recent posts
                    </h2>
                </div>

                <div class="mt-12 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-12">
                ${featuredCard(latest)}
                ${rest.map((p, i) => smallCard(p, i, rest.length)).join('\n                ')}
                </div>
            </div>
        </section>
    </main>`;
}

// ---- Home page: the five newest posts that have an article ----------------------------------------------------------------
function guidesList(posts) {
    return posts
        .filter((p) => p.hasPage)
        .slice(0, 5)
        .map((p) => `                <li>
                    <a href="${p.slug}.html" class="group flex gap-5 py-5 focus-visible:outline-none">
                        <div class="relative hidden aspect-[4/3] w-36 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-gradient-to-br ${p.gradient} sm:flex" aria-hidden="true">
                            <span class="absolute -top-4 -right-4 h-16 w-16 rounded-full bg-white/15"></span>
                            <span class="absolute -bottom-5 -left-3 h-14 w-14 rounded-full bg-white/10"></span>
                            <svg class="relative h-8 w-8 text-white" viewBox="0 0 20 20" fill="none">${icons[p.icon]}</svg>
                        </div>
                        <div class="min-w-0">
                            <p class="text-xs font-medium text-muted">${p.dateShort}</p>
                            <h3 class="mt-1 text-lg font-semibold text-ink transition-colors group-hover:text-accent group-focus-visible:text-accent dark:text-white">${esc(p.title)}</h3>
                            <p class="mt-1 text-sm leading-relaxed text-muted">${esc(p.excerpt)}</p>
                        </div>
                    </a>
                </li>`)
        .join('\n');
}

// ---- Build ----------------------------------------------------------------------------------------------------------------------------
function build() {
    missingImages.length = 0;
    const posts = loadPosts();
    const pagePosts = posts.filter((p) => p.hasPage);
    const boundary = /(<\/header>)[\s\S]*?(<footer)/;

    // The shared header, footer and search dialog come from an existing inner page.
    const shell = read(path.join(root, 'skills.html'));
    if (!boundary.test(shell)) throw new Error('skills.html: cannot find the header/footer boundary');

    // 1. Article pages
    for (const post of pagePosts) {
        let html = shell.replace(/<title>[\s\S]*?<\/title>/, () => `<title>${esc(post.title)} | Yora Jihun</title>
    <meta name="description" content="${attr(post.excerpt)}">
    ${MARKER}${post.file} - edit that file, not this one -->`);
        html = html.replace(boundary, (_, a, b) => `${a}\n\n    ${pageMain(post, posts)}\n\n    ${b}`);
        fs.writeFileSync(path.join(root, `${post.slug}.html`), html.replace(/[ \t]+$/gm, ''));
    }

    // 2. Remove pages of posts that were deleted or turned into cards only
    const keep = new Set(pagePosts.map((p) => `${p.slug}.html`));
    for (const f of fs.readdirSync(root).filter((n) => n.endsWith('.html') && !keep.has(n))) {
        if (read(path.join(root, f)).includes(MARKER)) {
            fs.unlinkSync(path.join(root, f));
            console.log(`removed ${f} (no matching post in posts/)`);
        }
    }

    // 3. Blog list
    const blogPath = path.join(root, 'blog.html');
    const blog = read(blogPath);
    if (!boundary.test(blog)) throw new Error('blog.html: cannot find the header/footer boundary');
    fs.writeFileSync(blogPath, blog.replace(boundary, (_, a, b) => `${a}\n\n    ${blogMain(posts)}\n\n    ${b}`).replace(/[ \t]+$/gm, ''));

    // 4. Home page Guides
    const indexPath = path.join(root, 'index.html');
    const home = read(indexPath);
    const guides = /(<section id="guides"[\s\S]*?<ul class="mt-8 divide-y divide-border border-y border-border">\n)([\s\S]*?)(\n\s*<\/ul>)/;
    if (!guides.test(home)) throw new Error('index.html: cannot find the Guides list');
    fs.writeFileSync(indexPath, home.replace(guides, (_, a, __, c) => `${a}${guidesList(posts)}${c}`));

    // 5. Search
    const q = (s) => JSON.stringify(s).replace(/</g, '\\u003c');
    const entries = posts.map((p) => `    { group: 'Guide', title: ${q(p.title)}, hint: ${q(p.searchHint)}, href: ${q(p.hasPage ? `${p.slug}.html` : 'blog.html')}, keywords: ${q(p.keywords)} },`);
    fs.mkdirSync(path.join(root, 'src/generated'), { recursive: true });
    fs.writeFileSync(
        path.join(root, 'src/generated/posts-search.js'),
        `// Generated by scripts/build-blog.mjs from posts/*.md. Do not edit by hand.\nexport const postSearch = [\n${entries.join('\n')}\n];\n`,
    );

    console.log(`blog built: ${posts.length} posts (${pagePosts.length} articles), newest first: ${posts.slice(0, 3).map((p) => p.slug).join(', ')}...`);
    for (const src of new Set(missingImages)) console.log(`note: image not found yet, skipped: ${src}`);
}

if (process.argv.includes('--watch')) {
    const run = () => {
        try {
            build();
            // Nudge the CSS build so any new Tailwind classes in the generated pages get compiled.
            const now = new Date();
            fs.utimesSync(path.join(root, 'src/main.css'), now, now);
        } catch (error) {
            console.error(`\n${error.message}\n`);
        }
    };
    run();
    let timer;
    fs.watch(postsDir, () => {
        clearTimeout(timer);
        timer = setTimeout(run, 250);
    });
    console.log('watching posts/ for changes...');
} else {
    try {
        build();
    } catch (error) {
        console.error(`\n${error.message}\n`);
        process.exit(1);
    }
}
